---
- include_vars: vars.yml
- name: Install packages
  become: yes
  apt:
    state: latest
    update_cache: true
    name: "{{ packages }}"
- name: Remove packages
  apt:
    name: "{{ removepackages }}"
    state: absent